title: Histoire numérique

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  -
    scope:
      path: ""
      type: "persons"
    values:
      layout: "person"
  -
    scope:
      path: ""
      type: "kinds"
    values:
      layout: "kind"

collections:
  pages:
    output: true
  events:
    output: true
  persons:
    output: true
  kinds:
    output: true

plugins:
  - jekyll-minifier
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
