title: Cultures numériques
author: Etienne Mineur

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  -
    scope:
      path: ""
      type: "persons"
    values:
      layout: "person"
  -
    scope:
      path: ""
      type: "kinds"
    values:
      layout: "kind"

collections:
  pages:
    output: true
  events:
    output: true
  persons:
    output: true
  kinds:
    output: true



exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - package.json
  - yarn.lock

plugins:
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-include-cache

sass:
    style: compressed

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: true
  remove_comments: true
  compress_css: false
  compress_javascript: false
  uglifier_args:
    harmony: true

picture:
  ignore_missing_images: true
  fast_build: true
  suppress_warnings: true
