backend:
  name: git-gateway
  branch: main
media_folder: 'assets/uploads'
locale: fr
slug:
  encoding: ascii
  clean_accents: true
collections:
  - name: events
    label: Evénements
    label_singular: Evénement
    folder: _events
    create: true
    sortable_fields: [year, kind]
    editor: { preview: false }
    fields:
      - { label: Titre, name: title }
      - { label: Type, name: kind, widget: relation, collection: kinds, display_fields: [title], value_field: "{{slug}}", search_fields: [title] }
      - { label: Année, name: year, widget: number, default: 2000, value_type: int, min: 1000, max: 3000, step: 1 }
      - { label: Personnes, name: persons, widget: relation, collection: persons, display_fields: [title], value_field: "{{slug}}", search_fields: [title], multiple: true, min: 0, required: false }
      - { label: Abstract, name: abstract, widget: text }
      - { label: Description, name: description, widget: markdown, minimal: true, required: false, buttons: [bold, link], editor_components: [], modes: [rich_text] }
      - { label: Image, name: image, widget: image, media_folder: /assets/images/events, allow_multiple: false, required: false }
      - { label: Galerie, name: gallery, widget: image, media_folder: /assets/images/events, allow_multiple: true, required: false, min: 0 }
      - { label: URL, name: url, required: false }
  - name: persons
    label: Personnes
    label_singular: Personne
    folder: _persons
    create: true
    editor: { preview: false }
    fields:
      - { label: Nom complet, name: title }
      - { label: Prénom, name: first_name }
      - { label: Nom, name: last_name }
      - { label: Image, name: image, widget: image, media_folder: '/assets/images/persons', allow_multiple: false }
      - { label: Description, name: description, required: false, widget: text }
      - { label: Naissance, name: birth, widget: number, default: 1950, value_type: int, min: 1000, max: 3000, step: 1 }
      - { label: Décès, name: death, widget: number, value_type: int, min: 1000, max: 3000, step: 1, required: false }
  - name: kinds
    label: Types d'événements
    label_singular: Type d'événement
    folder: _kinds
    create: true
    editor: { preview: false }
    fields:
      - { label: Titre, name: title }
      - { label: Description, name: description, widget: text, required: false }
